// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: api/proto/loan/v1/loan.proto

package loanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoanCalculator_CalculatePayment_FullMethodName = "/loan.v1.LoanCalculator/CalculatePayment"
)

// LoanCalculatorClient is the client API for LoanCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoanCalculatorClient interface {
	CalculatePayment(ctx context.Context, in *CalculatePaymentRequest, opts ...grpc.CallOption) (*CalculatePaymentResponse, error)
}

type loanCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanCalculatorClient(cc grpc.ClientConnInterface) LoanCalculatorClient {
	return &loanCalculatorClient{cc}
}

func (c *loanCalculatorClient) CalculatePayment(ctx context.Context, in *CalculatePaymentRequest, opts ...grpc.CallOption) (*CalculatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculatePaymentResponse)
	err := c.cc.Invoke(ctx, LoanCalculator_CalculatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanCalculatorServer is the server API for LoanCalculator service.
// All implementations must embed UnimplementedLoanCalculatorServer
// for forward compatibility.
type LoanCalculatorServer interface {
	CalculatePayment(context.Context, *CalculatePaymentRequest) (*CalculatePaymentResponse, error)
	mustEmbedUnimplementedLoanCalculatorServer()
}

// UnimplementedLoanCalculatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoanCalculatorServer struct{}

func (UnimplementedLoanCalculatorServer) CalculatePayment(context.Context, *CalculatePaymentRequest) (*CalculatePaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculatePayment not implemented")
}
func (UnimplementedLoanCalculatorServer) mustEmbedUnimplementedLoanCalculatorServer() {}
func (UnimplementedLoanCalculatorServer) testEmbeddedByValue()                        {}

// UnsafeLoanCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanCalculatorServer will
// result in compilation errors.
type UnsafeLoanCalculatorServer interface {
	mustEmbedUnimplementedLoanCalculatorServer()
}

func RegisterLoanCalculatorServer(s grpc.ServiceRegistrar, srv LoanCalculatorServer) {
	// If the following call panics, it indicates UnimplementedLoanCalculatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoanCalculator_ServiceDesc, srv)
}

func _LoanCalculator_CalculatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanCalculatorServer).CalculatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanCalculator_CalculatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanCalculatorServer).CalculatePayment(ctx, req.(*CalculatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoanCalculator_ServiceDesc is the grpc.ServiceDesc for LoanCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoanCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loan.v1.LoanCalculator",
	HandlerType: (*LoanCalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculatePayment",
			Handler:    _LoanCalculator_CalculatePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/loan/v1/loan.proto",
}
