// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/loan/v1/loan.proto

package loanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculationMethod int32

const (
	CalculationMethod_CALCULATION_METHOD_UNSPECIFIED CalculationMethod = 0 // defaults to PMT
	CalculationMethod_CALCULATION_METHOD_PMT         CalculationMethod = 1 // equal monthly payment (annuity)
)

// Enum value maps for CalculationMethod.
var (
	CalculationMethod_name = map[int32]string{
		0: "CALCULATION_METHOD_UNSPECIFIED",
		1: "CALCULATION_METHOD_PMT",
	}
	CalculationMethod_value = map[string]int32{
		"CALCULATION_METHOD_UNSPECIFIED": 0,
		"CALCULATION_METHOD_PMT":         1,
	}
)

func (x CalculationMethod) Enum() *CalculationMethod {
	p := new(CalculationMethod)
	*p = x
	return p
}

func (x CalculationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CalculationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_loan_v1_loan_proto_enumTypes[0].Descriptor()
}

func (CalculationMethod) Type() protoreflect.EnumType {
	return &file_api_proto_loan_v1_loan_proto_enumTypes[0]
}

func (x CalculationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CalculationMethod.Descriptor instead.
func (CalculationMethod) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_loan_v1_loan_proto_rawDescGZIP(), []int{0}
}

type CalculatePaymentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LoanAmount         float64                `protobuf:"fixed64,1,opt,name=loan_amount,json=loanAmount,proto3" json:"loan_amount,omitempty"`
	AnnualInterestRate float64                `protobuf:"fixed64,2,opt,name=annual_interest_rate,json=annualInterestRate,proto3" json:"annual_interest_rate,omitempty"`
	NumPayments        int32                  `protobuf:"varint,3,opt,name=num_payments,json=numPayments,proto3" json:"num_payments,omitempty"`
	CalculationMethod  CalculationMethod      `protobuf:"varint,4,opt,name=calculation_method,json=calculationMethod,proto3,enum=loan.v1.CalculationMethod" json:"calculation_method,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CalculatePaymentRequest) Reset() {
	*x = CalculatePaymentRequest{}
	mi := &file_api_proto_loan_v1_loan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePaymentRequest) ProtoMessage() {}

func (x *CalculatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loan_v1_loan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CalculatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_loan_v1_loan_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatePaymentRequest) GetLoanAmount() float64 {
	if x != nil {
		return x.LoanAmount
	}
	return 0
}

func (x *CalculatePaymentRequest) GetAnnualInterestRate() float64 {
	if x != nil {
		return x.AnnualInterestRate
	}
	return 0
}

func (x *CalculatePaymentRequest) GetNumPayments() int32 {
	if x != nil {
		return x.NumPayments
	}
	return 0
}

func (x *CalculatePaymentRequest) GetCalculationMethod() CalculationMethod {
	if x != nil {
		return x.CalculationMethod
	}
	return CalculationMethod_CALCULATION_METHOD_UNSPECIFIED
}

type CalculatePaymentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MonthlyPayment float64                `protobuf:"fixed64,1,opt,name=monthly_payment,json=monthlyPayment,proto3" json:"monthly_payment,omitempty"`
	// calculation_id is the UUID for this calculation (for audit trail and tracking)
	// Using UUID instead of sequential ID for:
	// - Distributed system compatibility (no lock contention)
	// - Security (prevents business volume exposure)
	CalculationId string `protobuf:"bytes,2,opt,name=calculation_id,json=calculationId,proto3" json:"calculation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePaymentResponse) Reset() {
	*x = CalculatePaymentResponse{}
	mi := &file_api_proto_loan_v1_loan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePaymentResponse) ProtoMessage() {}

func (x *CalculatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loan_v1_loan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CalculatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_loan_v1_loan_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatePaymentResponse) GetMonthlyPayment() float64 {
	if x != nil {
		return x.MonthlyPayment
	}
	return 0
}

func (x *CalculatePaymentResponse) GetCalculationId() string {
	if x != nil {
		return x.CalculationId
	}
	return ""
}

var File_api_proto_loan_v1_loan_proto protoreflect.FileDescriptor

const file_api_proto_loan_v1_loan_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/loan/v1/loan.proto\x12\aloan.v1\"\xda\x01\n" +
	"\x17CalculatePaymentRequest\x12\x1f\n" +
	"\vloan_amount\x18\x01 \x01(\x01R\n" +
	"loanAmount\x120\n" +
	"\x14annual_interest_rate\x18\x02 \x01(\x01R\x12annualInterestRate\x12!\n" +
	"\fnum_payments\x18\x03 \x01(\x05R\vnumPayments\x12I\n" +
	"\x12calculation_method\x18\x04 \x01(\x0e2\x1a.loan.v1.CalculationMethodR\x11calculationMethod\"j\n" +
	"\x18CalculatePaymentResponse\x12'\n" +
	"\x0fmonthly_payment\x18\x01 \x01(\x01R\x0emonthlyPayment\x12%\n" +
	"\x0ecalculation_id\x18\x02 \x01(\tR\rcalculationId*S\n" +
	"\x11CalculationMethod\x12\"\n" +
	"\x1eCALCULATION_METHOD_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CALCULATION_METHOD_PMT\x10\x012i\n" +
	"\x0eLoanCalculator\x12W\n" +
	"\x10CalculatePayment\x12 .loan.v1.CalculatePaymentRequest\x1a!.loan.v1.CalculatePaymentResponseB8Z6github.com/yun-cn/loan-engine/api/proto/loan/v1;loanv1b\x06proto3"

var (
	file_api_proto_loan_v1_loan_proto_rawDescOnce sync.Once
	file_api_proto_loan_v1_loan_proto_rawDescData []byte
)

func file_api_proto_loan_v1_loan_proto_rawDescGZIP() []byte {
	file_api_proto_loan_v1_loan_proto_rawDescOnce.Do(func() {
		file_api_proto_loan_v1_loan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_loan_v1_loan_proto_rawDesc), len(file_api_proto_loan_v1_loan_proto_rawDesc)))
	})
	return file_api_proto_loan_v1_loan_proto_rawDescData
}

var file_api_proto_loan_v1_loan_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_loan_v1_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_loan_v1_loan_proto_goTypes = []any{
	(CalculationMethod)(0),           // 0: loan.v1.CalculationMethod
	(*CalculatePaymentRequest)(nil),  // 1: loan.v1.CalculatePaymentRequest
	(*CalculatePaymentResponse)(nil), // 2: loan.v1.CalculatePaymentResponse
}
var file_api_proto_loan_v1_loan_proto_depIdxs = []int32{
	0, // 0: loan.v1.CalculatePaymentRequest.calculation_method:type_name -> loan.v1.CalculationMethod
	1, // 1: loan.v1.LoanCalculator.CalculatePayment:input_type -> loan.v1.CalculatePaymentRequest
	2, // 2: loan.v1.LoanCalculator.CalculatePayment:output_type -> loan.v1.CalculatePaymentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_loan_v1_loan_proto_init() }
func file_api_proto_loan_v1_loan_proto_init() {
	if File_api_proto_loan_v1_loan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_loan_v1_loan_proto_rawDesc), len(file_api_proto_loan_v1_loan_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_loan_v1_loan_proto_goTypes,
		DependencyIndexes: file_api_proto_loan_v1_loan_proto_depIdxs,
		EnumInfos:         file_api_proto_loan_v1_loan_proto_enumTypes,
		MessageInfos:      file_api_proto_loan_v1_loan_proto_msgTypes,
	}.Build()
	File_api_proto_loan_v1_loan_proto = out.File
	file_api_proto_loan_v1_loan_proto_goTypes = nil
	file_api_proto_loan_v1_loan_proto_depIdxs = nil
}
